# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Neha Arora
description: "Hi, I’m Neha Arora, a Data Scientist with a passion for building impactful, real-world solutions. This portfolio showcases some of my recent projects focused on driving business value. You can explore my GitHub, LinkedIn, or download my resume using the links below."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "New Delhi, India"
resume_url: /docs/Neha_Arora_Resume.pdf
avatar_image: /img/Profile_Picture.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/neha-arora-40665559/" # Add your linkedln handle
github: "https://github.com/Neha-2103/Neha-2103.github.io"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

